/*
 * 3gpp-pfd-management
 *
 * API for PFD management. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nef_models

// NetworkAreaInfo - Describes a network area information in which the NF service consumer requests the number of UEs.
type NetworkAreaInfo struct {

	// Contains a list of E-UTRA cell identities.
	Ecgis []Ecgi `json:"ecgis,omitempty" bson:"ecgis"`

	// Contains a list of NR cell identities.
	Ncgis []Ncgi `json:"ncgis,omitempty" bson:"ncgis"`

	// Contains a list of NG RAN nodes.
	GRanNodeIds []GlobalRanNodeId `json:"gRanNodeIds,omitempty" bson:"gRanNodeIds"`

	// Contains a list of tracking area identities.
	Tais []Tai `json:"tais,omitempty" bson:"tais"`
}
