/*
 * 3gpp-traffic-influence
 *
 * API for AF traffic influence © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nef_models

// EthFlowDescription - Identifies an Ethernet flow
type EthFlowDescription struct {
	DestMacAddr string `json:"destMacAddr,omitempty" bson:"destMacAddr"`

	EthType string `json:"ethType" bson:"ethType"`

	// Defines a packet filter of an IP flow.
	FDesc string `json:"fDesc,omitempty" bson:"fDesc"`

	FDir FlowDirection `json:"fDir,omitempty" bson:"fDir"`

	SourceMacAddr string `json:"sourceMacAddr,omitempty" bson:"sourceMacAddr"`

	VlanTags []string `json:"vlanTags,omitempty" bson:"vlanTags"`

	SrcMacAddrEnd string `json:"srcMacAddrEnd,omitempty" bson:"srcMacAddrEnd"`

	DestMacAddrEnd string `json:"destMacAddrEnd,omitempty" bson:"destMacAddrEnd"`
}
