/*
 * 3gpp-pfd-management
 *
 * API for PFD management. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nef_models

type PointAltitudeUncertainty struct {
	Shape SupportedGadShapes `json:"shape" bson:"shape"`

	Point *GeographicalCoordinates `json:"point" bson:"point"`

	Altitude float64 `json:"altitude" bson:"altitude"`

	UncertaintyEllipse *UncertaintyEllipse `json:"uncertaintyEllipse" bson:"uncertaintyEllipse"`

	UncertaintyAltitude float32 `json:"uncertaintyAltitude" bson:"uncertaintyAltitude"`

	Confidence int32 `json:"confidence" bson:"confidence"`
}
