/*
 * 3gpp-traffic-influence
 *
 * API for AF traffic influence © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nef_models

type WebsockNotifConfig struct {

	// string formatted according to IETF RFC 3986 identifying a referenced resource.
	WebsocketUri string `json:"websocketUri,omitempty" bson:"websocketUri"`

	// Set by the SCS/AS to indicate that the Websocket delivery is requested.
	RequestWebsocketUri bool `json:"requestWebsocketUri,omitempty" bson:"requestWebsocketUri"`
}
