/*
 * 3gpp-pfd-management
 *
 * API for PFD management. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nef_models

type CivicAddress struct {
	Country string `json:"country,omitempty" bson:"country"`

	A1 string `json:"A1,omitempty" bson:"A1"`

	A2 string `json:"A2,omitempty" bson:"A2"`

	A3 string `json:"A3,omitempty" bson:"A3"`

	A4 string `json:"A4,omitempty" bson:"A4"`

	A5 string `json:"A5,omitempty" bson:"A5"`

	A6 string `json:"A6,omitempty" bson:"A6"`

	PRD string `json:"PRD,omitempty" bson:"PRD"`

	POD string `json:"POD,omitempty" bson:"POD"`

	STS string `json:"STS,omitempty" bson:"STS"`

	HNO string `json:"HNO,omitempty" bson:"HNO"`

	HNS string `json:"HNS,omitempty" bson:"HNS"`

	LMK string `json:"LMK,omitempty" bson:"LMK"`

	LOC string `json:"LOC,omitempty" bson:"LOC"`

	NAM string `json:"NAM,omitempty" bson:"NAM"`

	PC string `json:"PC,omitempty" bson:"PC"`

	BLD string `json:"BLD,omitempty" bson:"BLD"`

	UNIT string `json:"UNIT,omitempty" bson:"UNIT"`

	FLR string `json:"FLR,omitempty" bson:"FLR"`

	ROOM string `json:"ROOM,omitempty" bson:"ROOM"`

	PLC string `json:"PLC,omitempty" bson:"PLC"`

	PCN string `json:"PCN,omitempty" bson:"PCN"`

	POBOX string `json:"POBOX,omitempty" bson:"POBOX"`

	ADDCODE string `json:"ADDCODE,omitempty" bson:"ADDCODE"`

	SEAT string `json:"SEAT,omitempty" bson:"SEAT"`

	RD string `json:"RD,omitempty" bson:"RD"`

	RDSEC string `json:"RDSEC,omitempty" bson:"RDSEC"`

	RDBR string `json:"RDBR,omitempty" bson:"RDBR"`

	RDSUBBR string `json:"RDSUBBR,omitempty" bson:"RDSUBBR"`

	PRM string `json:"PRM,omitempty" bson:"PRM"`

	POM string `json:"POM,omitempty" bson:"POM"`
}
