/*
 * 3gpp-pfd-management
 *
 * API for PFD management. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nef_models

type PfdData struct {

	// Each element uniquely external application identifier
	ExternalAppId string `json:"externalAppId" bson:"externalAppId"`

	// string formatted according to IETF RFC 3986 identifying a referenced resource.
	Self string `json:"self,omitempty" bson:"self"`

	// Contains the PFDs of the external application identifier. Each PFD is identified in the map via a key containing the PFD identifier.
	Pfds map[string]Pfd `json:"pfds" bson:"pfds"`

	// Unsigned integer identifying a period of time in units of seconds with \"nullable=true\" property.
	AllowedDelay int32 `json:"allowedDelay,omitempty" bson:"allowedDelay"`

	// Unsigned integer identifying a period of time in units of seconds with \"readOnly=true\" property.
	CachingTime int32 `json:"cachingTime,omitempty" bson:"cachingTime"`
}
