/*
 * 3gpp-pfd-management
 *
 * API for PFD management. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nef_models

type PfdReport struct {

	// Identifies the external application identifier(s) which PFD(s) are not added or modified successfully
	ExternalAppIds []string `json:"externalAppIds" bson:"externalAppIds"`

	FailureCode FailureCode `json:"failureCode" bson:"failureCode"`

	// Unsigned integer identifying a period of time in units of seconds.
	CachingTime int32 `json:"cachingTime,omitempty" bson:"cachingTime"`

	LocationArea *UserPlaneLocationArea `json:"locationArea,omitempty" bson:"locationArea"`
}
