/*
 * 3gpp-pfd-management
 *
 * API for PFD management. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nef_models

type Pfd struct {

	// Identifies a PDF of an application identifier.
	PfdId string `json:"pfdId" bson:"pfdId"`

	// Represents a 3-tuple with protocol, server ip and server port for UL/DL application traffic. The content of the string has the same encoding as the IPFilterRule AVP value as defined in IETF RFC 6733.
	FlowDescriptions []string `json:"flowDescriptions,omitempty" bson:"flowDescriptions"`

	// Indicates a URL or a regular expression which is used to match the significant parts of the URL.
	Urls []string `json:"urls,omitempty" bson:"urls"`

	// Indicates an FQDN or a regular expression as a domain name matching criteria.
	DomainNames []string `json:"domainNames,omitempty" bson:"domainNames"`

	DnProtocol DomainNameProtocol `json:"dnProtocol,omitempty" bson:"dnProtocol"`
}
