/*
 * 3gpp-pfd-management
 *
 * API for PFD management. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nef_models

type GlobalRanNodeId struct {
	PlmnId *PlmnId `json:"plmnId" bson:"plmnId"`

	N3IwfId string `json:"n3IwfId,omitempty" bson:"n3IwfId"`

	GNbId *GNbId `json:"gNbId,omitempty" bson:"gNbId"`

	NgeNbId string `json:"ngeNbId,omitempty" bson:"ngeNbId"`

	WagfId string `json:"wagfId,omitempty" bson:"wagfId"`

	TngfId string `json:"tngfId,omitempty" bson:"tngfId"`

	Nid string `json:"nid,omitempty" bson:"nid"`

	ENbId string `json:"eNbId,omitempty" bson:"eNbId"`
}
