/*
 * 3gpp-traffic-influence
 *
 * API for AF traffic influence © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nef_models

type DnaiChangeType string

// List of DnaiChangeType
const (
	DnaiChangeType_EARLY      DnaiChangeType = "EARLY"
	DnaiChangeType_EARLY_LATE DnaiChangeType = "EARLY_LATE"
	DnaiChangeType_LATE       DnaiChangeType = "LATE"
)
