/*
 * 3gpp-traffic-influence
 *
 * API for AF traffic influence © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nef_models

type RouteToLocation struct {
	Dnai string `json:"dnai" bson:"dnai"`

	RouteInfo *RouteInformation `json:"routeInfo,omitempty" bson:"routeInfo"`

	RouteProfId string `json:"routeProfId,omitempty" bson:"routeProfId"`
}
