/*
 * 3gpp-traffic-influence
 *
 * API for AF traffic influence © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nef_models

type FlowDirection string

// List of FlowDirection
const (
	FlowDirection_DOWNLINK      FlowDirection = "DOWNLINK"
	FlowDirection_UPLINK        FlowDirection = "UPLINK"
	FlowDirection_BIDIRECTIONAL FlowDirection = "BIDIRECTIONAL"
	FlowDirection_UNSPECIFIED   FlowDirection = "UNSPECIFIED"
)
