/*
 * 3gpp-traffic-influence
 *
 * API for AF traffic influence © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nef_models

import (
	"time"
)

// TemporalValidity - Indicates the time interval(s) during which the AF request is to be applied
type TemporalValidity struct {
	StartTime *time.Time `json:"startTime,omitempty" bson:"startTime"`

	StopTime *time.Time `json:"stopTime,omitempty" bson:"stopTime"`
}
