/*
 * 3gpp-traffic-influence
 *
 * API for AF traffic influence © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nef_models

type RouteInformation struct {
	Ipv4Addr string `json:"ipv4Addr,omitempty" bson:"ipv4Addr"`

	Ipv6Addr string `json:"ipv6Addr,omitempty" bson:"ipv6Addr"`

	PortNumber int32 `json:"portNumber" bson:"portNumber"`
}
