/*
 * 3gpp-pfd-management
 *
 * API for PFD management. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nef_models

type GeographicArea struct {
	Shape SupportedGadShapes `json:"shape" bson:"shape"`

	Point *GeographicalCoordinates `json:"point" bson:"point"`

	Uncertainty float32 `json:"uncertainty" bson:"uncertainty"`

	UncertaintyEllipse *UncertaintyEllipse `json:"uncertaintyEllipse" bson:"uncertaintyEllipse"`

	Confidence int32 `json:"confidence" bson:"confidence"`

	PointList []GeographicalCoordinates `json:"pointList" bson:"pointList"`

	Altitude float64 `json:"altitude" bson:"altitude"`

	UncertaintyAltitude float32 `json:"uncertaintyAltitude" bson:"uncertaintyAltitude"`

	InnerRadius int32 `json:"innerRadius" bson:"innerRadius"`

	UncertaintyRadius float32 `json:"uncertaintyRadius" bson:"uncertaintyRadius"`

	OffsetAngle int32 `json:"offsetAngle" bson:"offsetAngle"`

	IncludedAngle int32 `json:"includedAngle" bson:"includedAngle"`
}
