/*
 * Nbsf_Management
 *
 * Binding Support Management Service API. © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type BindingResp struct {

	// Fully Qualified Domain Name
	PcfSmFqdn string `json:"pcfSmFqdn,omitempty" bson:"pcfSmFqdn"`

	// IP end points of the PCF hosting the Npcf_SMPolicyControl service.
	PcfSmIpEndPoints []IpEndPoint `json:"pcfSmIpEndPoints,omitempty" bson:"pcfSmIpEndPoints"`
}
